config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pages#home"
  # get "/", to: "pages#home"
  get "/musume", to: "musume#index"
  get "/musume/new", to: "musume#new", as:"new_mesume"
  get "/chartable_view", to: "chartable_view#index"

  post "/", to: "pages#home"

  # get "/musume/new", to: "resumes#new"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/museum.rb
class Museum < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/chartable_view_controller.rb
class ChartableViewController < ApplicationController
    def chartable
        test
    end

    def req_api(url)
        # resopnse = 
    end
end

app/controllers/musume_controller.rb
class MusumeController < ApplicationController
    def index
        # @message = "This is title"
        # render(html: "hello")
        # render "musume/index"

    end

    def new
        
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chartable_view_helper.rb
module ChartableViewHelper
end

app/helpers/musume_helper.rb
module MusumeHelper
end

app/views/chartable_view/index.html.erb
<%# <h1>

</h1> %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rtitest</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>

app/views/musume/index.html.erb
<%# <a href="/musume/new">新增館藏</a> %>
<%# <a href="<%#= new_mesume_path">新增館藏</#a> %>

<%= link_to "新增藏館", new_mesume_path %>

<p><%= @message %></p>

app/views/musume/new.html.erb
<h1>新增館藏</h1>

<%#= new_mesume_path %>

<form action="/musume" method="post">

    <div>
        標題
        <input type="text" name="title">
    </div>

    <div>
        內文
        <textarea name="content" id=""></textarea>
    </div>
    <input type="submit" value="新增">
</form>